version: "3.10"

services:
  web_cost_manager:
    container_name: cost_manager
    build:
      context: ./
    volumes:
      - ./app/:/home/mikita/Documents/PycharmProjects/cost_manager/src
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "python ./src/manage.py makemigrations && 
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_cost_manager

  db_cost_manager:
    image: postgres:14.5-alpine
    container_name: db_cost_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=officeuser
      - POSTGRES_PASSWORD=officeuser123
      - POSTGRES_DB=cost_manager
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:alpine
    restart: always

  celery:
    container_name: celery
    restart: always
    build: ./
    command: celery --workdir=./src -A src worker
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web_cost_manager
      - db_cost_manager

  celery-beat:
    container_name: celery-beat
    build: ./
    command: celery --workdir=./src -A src beat -l info
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - web_cost_manager
      - db_cost_manager

volumes:
  postgres_data: